### ISSUE TITLE
로또 시뮬레이션 기능 구현

### ISSUE THREAD

**Issue by jyshoon** [gnujylee/assignment#3]
- 2번 메뉴에 해당

- 답을 하나 생성
- 아래의 알고리즘을 로또 당첨 시뮬레이션 구현
  count = 0; 
  do {
     count ++;
     newLotto 생성
    답과 newLotto 비교
    if (답과 정확히 일치) 
       break;
  } while (1);
  count 출력
  count * 1000원 출력

**Comment by gnujylee** [comment]
시뮬레이션 기능을 추가하고
실행용 exe파일을 생성하였음
